-- Cybersécurité Accessible Database Schema
-- PostgreSQL 15
-- Sprint 1: Database Initialization

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table 1: Detected Network Devices (EF-4.1.x)
CREATE TABLE IF NOT EXISTS devices (
    id SERIAL PRIMARY KEY,
    ip_address INET NOT NULL,
    mac_address MACADDR NOT NULL,
    manufacturer VARCHAR(255),
    device_type VARCHAR(100),
    first_seen TIMESTAMP DEFAULT NOW(),
    last_seen TIMESTAMP DEFAULT NOW(),
    is_flagged BOOLEAN DEFAULT FALSE,
    is_marked_safe BOOLEAN DEFAULT FALSE,
    scan_id UUID,
    UNIQUE(ip_address, mac_address)
);

-- Table 2: Threat Database - MAC Addresses (EF-4.2.1)
CREATE TABLE IF NOT EXISTS threat_macs (
    id SERIAL PRIMARY KEY,
    mac_address MACADDR UNIQUE NOT NULL,
    threat_type VARCHAR(100) NOT NULL,
    description TEXT,
    severity VARCHAR(20) CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    added_date TIMESTAMP DEFAULT NOW(),
    source VARCHAR(255)
);

-- Table 3: Phishing URL Blacklist (EF-4.3.2)
CREATE TABLE IF NOT EXISTS phishing_urls (
    id SERIAL PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,
    domain VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100),
    added_date TIMESTAMP DEFAULT NOW(),
    last_verified TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

-- Table 4: Security Alerts (EF-4.4.2)
CREATE TABLE IF NOT EXISTS alerts (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL CHECK (alert_type IN ('device', 'phishing', 'network')),
    severity VARCHAR(20) CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    details JSONB,
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'resolved', 'dismissed')),
    justification TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(100)
);

-- Table 5: Scan History (Performance tracking - ENF-5.2.1)
CREATE TABLE IF NOT EXISTS scan_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    scan_date TIMESTAMP DEFAULT NOW(),
    devices_found INTEGER DEFAULT 0,
    new_devices INTEGER DEFAULT 0,
    threats_detected INTEGER DEFAULT 0,
    scan_duration_seconds INTEGER,
    network_range VARCHAR(50),
    status VARCHAR(20) CHECK (status IN ('completed', 'failed', 'partial'))
);

-- Table 6: API Keys (Authentication)
CREATE TABLE IF NOT EXISTS api_keys (
    id SERIAL PRIMARY KEY,
    key_name VARCHAR(100) UNIQUE NOT NULL,
    key_hash VARCHAR(255) NOT NULL,
    component VARCHAR(50) CHECK (component IN ('agent', 'extension', 'admin')),
    created_at TIMESTAMP DEFAULT NOW(),
    last_used TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_devices_mac ON devices(mac_address);
CREATE INDEX IF NOT EXISTS idx_devices_ip ON devices(ip_address);
CREATE INDEX IF NOT EXISTS idx_devices_last_seen ON devices(last_seen);
CREATE INDEX IF NOT EXISTS idx_threat_macs_mac ON threat_macs(mac_address);
CREATE INDEX IF NOT EXISTS idx_phishing_urls_domain ON phishing_urls(domain);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_scan_history_date ON scan_history(scan_date);

-- Create a view for active threats
CREATE OR REPLACE VIEW active_threats AS
SELECT 
    a.id,
    a.alert_type,
    a.severity,
    a.title,
    a.description,
    a.created_at,
    CASE 
        WHEN a.alert_type = 'device' THEN d.ip_address::TEXT
        ELSE NULL
    END AS related_ip
FROM alerts a
LEFT JOIN devices d ON (a.details->>'mac_address')::MACADDR = d.mac_address
WHERE a.status = 'active'
ORDER BY a.created_at DESC;

-- Create a function to update device last_seen timestamp
CREATE OR REPLACE FUNCTION update_device_last_seen()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_seen = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update last_seen on device updates
CREATE TRIGGER trigger_update_device_last_seen
    BEFORE UPDATE ON devices
    FOR EACH ROW
    EXECUTE FUNCTION update_device_last_seen();

-- Comments for documentation
COMMENT ON TABLE devices IS 'Network devices discovered by scan agent (EF-4.1.x)';
COMMENT ON TABLE threat_macs IS 'Static database of suspicious MAC addresses (EF-4.2.1)';
COMMENT ON TABLE phishing_urls IS 'Blacklist of phishing URLs (EF-4.3.2)';
COMMENT ON TABLE alerts IS 'Security alerts generated by the system (EF-4.4.x)';
COMMENT ON TABLE scan_history IS 'Historical record of network scans';

-- Grant permissions to application user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;